# -*- coding: utf-8 -*-
"""cross validation score

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrNt4iIjP8Y3KapNIU0pTnRMhjdj2Whv

# latihan cross validation score
"""

import sklearn
from sklearn import datasets

iris = datasets.load_iris()

#mendefenisikan atribut dan label pada data
x = iris.data
y = iris.target

from sklearn import tree

#membuat model dengan decision tree classifier
clf = tree.DecisionTreeClassifier()

from sklearn.model_selection import cross_val_score

#mengevaluasi modell dengan cross_val_score
scores = cross_val_score(clf, x, y, cv=5)

scores

